### PR TITLE
Fix bug in SymbolicFunction when robot has extra dofs.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
@pFernbach can you validate that this fixes your issue ?

**Comment by jmirabel** [comment]
@pFernbach mind that I just force-pushed.

**Comment by nim65s** [comment]
Hi,

Thanks @jmirabel for this. It fixed the tests on my side in the 4.9.0 release on hpp-rbprm-corba, so I included this in #112 .

**Comment by pFernbach** [comment]
I confirm that it solve my issue. Thanks.

**Comment by jmirabel** [comment]
@nim65s should I merge or close ?

**Comment by nim65s** [comment]
This can be closed :)

**Pull request closed without merging**
