### PR TITLE
[WIP] Fix backtracking line search.

### PR DESCRIPTION
**Pull request by jmirabel**
I think I understood the reason why the solver requires plenty of steps to converge. The default line search is a fixed sequence `alpha = (1-K)*A + K * a`, for A = 0.95, alpha_0 = 0.2 and K = 0.8. The taken step never reach 1., which should be reached when within the right basin of attraction.

I tried the following:
- a fixed sequence with parameters K = 0.6, A = 1: the convergence is slightly better.
- a backtracking line search, the convergence seems already better
- a backtracking line search with an upper bound for the step norm (see my comment in the code): the convergence seems a lot better.

Backtracking line search poses a problem with contact constraints. The shapes are always projected to the edge of the surfaces. This is an issue of the contact constraint and not of the solver itself, but it has to be addressed or the default line search should be dependent upon the constraints.

The last strategy needs one extra parameter which ought to be scaled (maybe using the configuration space bounds).

One good thing to do would be to define a standard problem and benchmark the different line searches on it. I think it could be based on the manipulator available in hpp::pinocchio::unittest.

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
What do you mean by backtracking line search ?

**Comment by jmirabel** [comment]
I mean the implementation of this: https://en.wikipedia.org/wiki/Backtracking_line_search

**Comment by jmirabel** [comment]
Roughly speaking, it corresponds to looking for a step that makes the function decrease more than the decrease of the linearized function with a reduced coefficient, i.e. it compares || F(t) || with  || c * F'(0) * t + F(0) ||, where c < 1 and F(t) = f( x_0 + t * dir), f being the function the zero of whose we seek.

**Comment by jmirabel** [comment]
At the moment, I didn't change the default line search so it won't change anything. For the benchmarks, we can put `ps.setDefaultLineSearchType ('Backtracking')`.
However, I would prefer to have a cpp file in this repo to test that. It's a bit more work.

**Pull request merged**
